'use server';

import { revalidatePath } from 'next/cache';
import { getActiveOrganizationContext } from '@/lib/organization-context';
import { requireAuthenticatedUser } from '@/lib/supabase/auth-helpers';
import { createClient } from '@/lib/supabase/server';

function value(formData: FormData, key: string) { return String(formData.get(key) ?? '').trim(); }
async function context() { const user = await requireAuthenticatedUser('/app/billing'); const organization = await getActiveOrganizationContext(user.id); if (!organization) throw new Error('No active organization is available.'); return organization; }

export async function createInvoiceAction(formData: FormData): Promise<void> { const org = await context(); const supabase = await createClient(); const items = JSON.parse(value(formData, 'items') || '[]'); const { error } = await supabase.rpc('create_invoice', { p_organization_id: org.organizationId, p_patient_id: value(formData, 'patientId'), p_appointment_id: (value(formData, 'appointmentId') || null) as unknown as string, p_encounter_id: (value(formData, 'encounterId') || null) as unknown as string, p_currency: value(formData, 'currency') || 'CAD', p_due_date: (value(formData, 'dueDate') || null) as unknown as string, p_discount: Number(value(formData, 'discount') || 0), p_notes: (value(formData, 'notes') || null) as unknown as string, p_items: items }); if (error) throw error; revalidatePath('/app/billing/invoices'); }
export async function issueInvoiceAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('issue_invoice', { p_invoice_id: value(formData, 'invoiceId') }); if (error) throw error; revalidatePath('/app/billing/invoices'); }
export async function voidInvoiceAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('void_invoice', { p_invoice_id: value(formData, 'invoiceId'), p_reason: 'Voided by authorized billing staff' }); if (error) throw error; revalidatePath('/app/billing/invoices'); }
export async function recordPaymentAction(formData: FormData): Promise<void> { const org = await context(); const supabase = await createClient(); const { error } = await supabase.rpc('record_payment', { p_organization_id: org.organizationId, p_patient_id: value(formData, 'patientId'), p_method: value(formData, 'method'), p_amount: Number(value(formData, 'amount')), p_currency: value(formData, 'currency') || 'CAD', p_reference: value(formData, 'reference') || '', p_received_at: value(formData, 'receivedAt') || undefined, p_notes: value(formData, 'notes') || undefined }); if (error) throw error; revalidatePath('/app/billing/payments'); }
export async function allocatePaymentAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('allocate_payment', { p_payment_id: value(formData, 'paymentId'), p_invoice_id: value(formData, 'invoiceId'), p_amount: Number(value(formData, 'amount')) }); if (error) throw error; revalidatePath('/app/billing/payments'); revalidatePath('/app/billing/invoices'); }
export async function generateReceiptAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('generate_receipt', { p_payment_id: value(formData, 'paymentId') }); if (error) throw error; revalidatePath('/app/billing/receipts'); }
export async function saveTaxProfileAction(formData: FormData): Promise<void> { const org = await context(); const supabase = await createClient(); const { error } = await supabase.rpc('update_tax_profile', { p_organization_id: org.organizationId, p_id: (value(formData, 'id') || null) as unknown as string, p_name: value(formData, 'name'), p_jurisdiction: value(formData, 'jurisdiction') || 'CA', p_rates: JSON.parse(value(formData, 'rates') || '[]'), p_is_default: formData.get('isDefault') === 'on', p_status: 'active' }); if (error) throw error; revalidatePath('/app/billing/settings'); }
export async function saveDiscountRuleAction(formData: FormData): Promise<void> { const org = await context(); const supabase = await createClient(); const { error } = await supabase.rpc('update_discount_rules', { p_organization_id: org.organizationId, p_id: (value(formData, 'id') || null) as unknown as string, p_name: value(formData, 'name'), p_discount_type: value(formData, 'discountType'), p_value: Number(value(formData, 'value')), p_currency: value(formData, 'currency') || 'CAD', p_status: 'active' }); if (error) throw error; revalidatePath('/app/billing/settings'); }
