import { Card } from '@medbookpro/ui';
import { getActiveOrganizationContext } from '@/lib/organization-context';
import { requireAuthenticatedUser } from '@/lib/supabase/auth-helpers';
import { createClient } from '@/lib/supabase/server';
import { saveTemplateAction } from '../actions';

export default async function TemplatesPage() {
  const user = await requireAuthenticatedUser('/app/communications/templates'); const org = await getActiveOrganizationContext(user.id); if (!org) return null;
  const supabase = await createClient(); const { data: templates } = await supabase.from('notification_templates').select('id, template_key, channel, version, status, language, subject, body').order('template_key');
  return <main className="min-h-screen bg-slate-50 px-6 py-12 text-slate-950"><div className="mx-auto max-w-6xl"><h1 className="text-4xl font-semibold tracking-tight">Notification templates</h1><p className="mt-3 text-slate-600">Editing creates a new version. These templates are not delivered externally.</p><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_2fr]"><Card><h2 className="text-xl font-semibold">New version</h2><form action={saveTemplateAction} className="mt-4 space-y-3"><input type="hidden" name="templateId" value="" /><label className="block text-sm">Key<input required name="templateKey" className="mt-1 w-full rounded border p-2" placeholder="appointment.reminder" /></label><label className="block text-sm">Channel<select name="channel" className="mt-1 w-full rounded border p-2"><option>email</option><option>sms</option><option>internal</option></select></label><label className="block text-sm">Language<input name="language" defaultValue="en-CA" className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Subject<input name="subject" className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Body<textarea required name="body" rows={6} className="mt-1 w-full rounded border p-2" /></label><button className="rounded bg-blue-700 px-4 py-2 font-semibold text-white" type="submit">Save template</button></form></Card><Card><h2 className="text-xl font-semibold">Versions</h2><div className="mt-4 space-y-3">{(templates ?? []).map((template) => <article className="rounded border p-3" key={template.id}><p className="font-semibold">{template.template_key} · {template.channel} · v{template.version}</p><p className="text-sm text-slate-600">{template.status} · {template.language} · {template.subject ?? 'No subject'}</p></article>)}{!templates?.length && <p className="text-sm text-slate-600">No templates have been created.</p>}</div></Card></div></div></main>;
}
