'use server';

import { revalidatePath } from 'next/cache';
import { getActiveOrganizationContext } from '@/lib/organization-context';
import { requireAuthenticatedUser } from '@/lib/supabase/auth-helpers';
import { createClient } from '@/lib/supabase/server';

function value(formData: FormData, key: string) { return String(formData.get(key) ?? '').trim(); }
async function context() { const user = await requireAuthenticatedUser('/app/communications'); const organization = await getActiveOrganizationContext(user.id); if (!organization) throw new Error('No active organization is available.'); return organization; }

export async function saveTemplateAction(formData: FormData): Promise<void> { const org = await context(); const supabase = await createClient(); const { error } = await supabase.rpc('update_templates', { p_organization_id: org.organizationId, p_template_id: value(formData, 'templateId') || '00000000-0000-0000-0000-000000000000', p_template_key: value(formData, 'templateKey'), p_channel: value(formData, 'channel'), p_subject: value(formData, 'subject') || '', p_body: value(formData, 'body'), p_variables: {}, p_language: value(formData, 'language') || 'en-CA', p_status: 'active' }); if (error) throw error; revalidatePath('/app/communications/templates'); }
export async function sendMockNotificationAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('send_mock_notification', { p_queue_id: value(formData, 'queueId') }); if (error) throw error; revalidatePath('/app/communications/queue'); }
export async function cancelNotificationAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('cancel_notification', { p_queue_id: value(formData, 'queueId'), p_reason: 'Cancelled by authorized staff' }); if (error) throw error; revalidatePath('/app/communications/queue'); }
export async function savePreferencesAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const patientId = value(formData, 'patientId'); const { error } = await supabase.rpc('update_preferences', { p_patient_id: patientId, p_appointment_reminders: formData.get('appointmentReminders') === 'on', p_marketing_opt_in: formData.get('marketingOptIn') === 'on', p_sms_enabled: formData.get('smsEnabled') === 'on', p_email_enabled: formData.get('emailEnabled') === 'on', p_preferred_language: value(formData, 'preferredLanguage') || 'en-CA', p_quiet_hours: {} }); if (error) throw error; revalidatePath(`/app/patients/${patientId}/communication-preferences`); }
export async function saveSettingsAction(formData: FormData): Promise<void> { await context(); const supabase = await createClient(); const { error } = await supabase.rpc('update_notification_settings', { p_default_reminder_minutes: Number(value(formData, 'defaultReminderMinutes')), p_branding_placeholder: {}, p_default_sender: value(formData, 'defaultSender') || '', p_timezone: value(formData, 'timezone') || 'America/Edmonton' }); if (error) throw error; revalidatePath('/app/communications/settings'); }
