import { Card } from '@medbookpro/ui';
import { getActiveOrganizationContext } from '@/lib/organization-context';
import { requireAuthenticatedUser } from '@/lib/supabase/auth-helpers';
import { createClient } from '@/lib/supabase/server';

export default async function DocumentMetadataPage({ params }: { params: Promise<{ documentId: string }> }) {
  const { documentId } = await params; const user = await requireAuthenticatedUser(`/app/documents/${documentId}`); const context = await getActiveOrganizationContext(user.id); if (!context) return null; const supabase = await createClient();
  const { data: document, error } = await supabase.from('documents').select('id,title,description,mime_type,file_size_bytes,checksum_placeholder,storage_provider_placeholder,storage_path_placeholder,retention_status,archived,created_at').eq('id', documentId).eq('organization_id', context.organizationId).maybeSingle(); if (error) throw error; if (!document) return <main className="p-8">Document not found.</main>;
  const { data: versions } = await supabase.from('document_versions').select('id,version_number,is_current,previous_version_id,created_at,mime_type,file_size_bytes').eq('document_id', documentId).eq('organization_id', context.organizationId).order('version_number', { ascending: false });
  return <main className="min-h-screen bg-slate-50 px-6 py-12 text-slate-950"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-semibold">{document.title}</h1><Card className="mt-8"><h2 className="text-xl font-semibold">Metadata</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Description', document.description ?? '—'], ['MIME type', document.mime_type ?? '—'], ['Size', document.file_size_bytes ? `${document.file_size_bytes} bytes` : '—'], ['Retention', document.retention_status], ['Storage provider', document.storage_provider_placeholder ?? 'Not connected'], ['Storage path', document.storage_path_placeholder ?? 'Not assigned']].map(([label,value]) => <div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl></Card><Card className="mt-6"><h2 className="text-xl font-semibold">Version history</h2><div className="mt-4 space-y-3">{versions?.map((version) => <p key={version.id} className="text-sm">Version {version.version_number} · {version.is_current ? 'current' : 'previous'} · {version.mime_type ?? 'metadata only'}</p>)}</div></Card></div></main>;
}
