import { Card } from '@medbookpro/ui';
import { getActiveOrganizationContext } from '@/lib/organization-context';
import { requireAuthenticatedUser } from '@/lib/supabase/auth-helpers';
import { createClient } from '@/lib/supabase/server';
import { cancelNotificationAction, sendMockNotificationAction } from '../actions';

export default async function QueuePage() {
  const user = await requireAuthenticatedUser('/app/communications/queue'); const org = await getActiveOrganizationContext(user.id); if (!org) return null;
  const supabase = await createClient(); const { data: queue } = await supabase.from('notification_queue').select('id, channel, status, provider, scheduled_send_at, attempt_count, failure_reason').order('created_at', { ascending: false }).limit(50); const { data: deliveries } = await supabase.from('notification_deliveries').select('id, queue_id, provider, status, provider_message_id, delivered_at').order('created_at', { ascending: false }).limit(50);
  return <main className="min-h-screen bg-slate-50 px-6 py-12 text-slate-950"><div className="mx-auto max-w-6xl"><h1 className="text-4xl font-semibold tracking-tight">Notification queue</h1><p className="mt-3 text-slate-600">Queue status and mock delivery log. Destination addresses are intentionally not displayed.</p><Card className="mt-8"><h2 className="text-xl font-semibold">Queue</h2><div className="mt-4 space-y-3">{(queue ?? []).map((item) => <article className="rounded border p-3" key={item.id}><p className="font-semibold">{item.channel} · {item.status} · attempt {item.attempt_count}</p><p className="text-sm text-slate-600">{item.provider} · {item.scheduled_send_at}</p><div className="mt-2 flex gap-2">{['pending', 'retrying', 'failed'].includes(item.status) && <form action={sendMockNotificationAction}><input type="hidden" name="queueId" value={item.id} /><button className="rounded bg-blue-700 px-3 py-1 text-sm font-semibold text-white" type="submit">Send mock</button></form>}{!['sent', 'cancelled'].includes(item.status) && <form action={cancelNotificationAction}><input type="hidden" name="queueId" value={item.id} /><button className="rounded border px-3 py-1 text-sm" type="submit">Cancel</button></form>}</div></article>)}{!queue?.length && <p className="text-sm text-slate-600">No notifications are queued.</p>}</div></Card><Card className="mt-6"><h2 className="text-xl font-semibold">Delivery log</h2><div className="mt-4 space-y-2">{(deliveries ?? []).map((delivery) => <p className="rounded border p-3 text-sm" key={delivery.id}>{delivery.provider} · {delivery.status} · {delivery.provider_message_id}</p>)}{!deliveries?.length && <p className="text-sm text-slate-600">No deliveries recorded.</p>}</div></Card></div></main>;
}
